// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyr_sIEMxLWFtYmGxlUZV5N00oOFGxRA',
    appId: '1:382529705358:web:be5656d7bc8a8ad60140df',
    messagingSenderId: '382529705358',
    projectId: 'housetainer-2fd6f',
    authDomain: 'housetainer-2fd6f.firebaseapp.com',
    storageBucket: 'housetainer-2fd6f.appspot.com',
    measurementId: 'G-NHKT4FJ03W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCxvlP9M2sXUaeja8-AbcNXZXjZ2xkFo',
    appId: '1:382529705358:android:ce91f8b3ad2e85f30140df',
    messagingSenderId: '382529705358',
    projectId: 'housetainer-2fd6f',
    storageBucket: 'housetainer-2fd6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-AfXplfGmk1USBP-rx4-EIXEe3ROGa8',
    appId: '1:382529705358:ios:0a044742aab251150140df',
    messagingSenderId: '382529705358',
    projectId: 'housetainer-2fd6f',
    storageBucket: 'housetainer-2fd6f.appspot.com',
    iosClientId: '382529705358-fgn973ucnvjrefhp4dlcaks0tjkjd03u.apps.googleusercontent.com',
    iosBundleId: 'com.example.housetainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-AfXplfGmk1USBP-rx4-EIXEe3ROGa8',
    appId: '1:382529705358:ios:0a044742aab251150140df',
    messagingSenderId: '382529705358',
    projectId: 'housetainer-2fd6f',
    storageBucket: 'housetainer-2fd6f.appspot.com',
    iosClientId: '382529705358-fgn973ucnvjrefhp4dlcaks0tjkjd03u.apps.googleusercontent.com',
    iosBundleId: 'com.example.housetainer',
  );
}
